name: Generate AOSP Keyboxes (Highly Custom)

on:
  workflow_dispatch:
    inputs:
      custom_device_id:
        type: string
        default: ""
      custom_cn:
        type: string
        default: "AOSP"
      custom_org:
        type: string
        default: "Android Open Source Project"
      custom_country:
        type: string
        default: "US"
      custom_start_date:
        type: string
        default: ""
      root_validity_days:
        type: string
        default: "7300"
      leaf_validity_days:
        type: string
        default: "3650"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get install -y faketime

    - name: Apply Custom Certificate Subject & Validity Days
      run: |
        sed -i 's/AOSP Test/${{ inputs.custom_cn }}/g' aosp_keybox_generator.py
        sed -i 's/O=Android Open Source Project/O=${{ inputs.custom_org }}/g' aosp_keybox_generator.py
        sed -i 's/C=US/C=${{ inputs.custom_country }}/g' aosp_keybox_generator.py
        sed -i 's/-days 7300/-days ${{ inputs.root_validity_days }}/g' aosp_keybox_generator.py
        sed -i 's/-days 3650/-days ${{ inputs.leaf_validity_days }}/g' aosp_keybox_generator.py

    - name: Generate Keyboxes
      run: |
        if [ -n "${{ inputs.custom_start_date }}" ]; then
          faketime "${{ inputs.custom_start_date }}" python aosp_keybox_generator.py
        else
          python aosp_keybox_generator.py
        fi

    - name: Apply Custom DeviceID
      if: ${{ inputs.custom_device_id != '' }}
      run: |
        sed -i 's/DeviceID="[^"]*"/DeviceID="${{ inputs.custom_device_id }}"/g' *-aosp-chain*/keybox.xml

    - name: Upload Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: AOSP-Keyboxes-Custom-Pack
        path: |
          *-aosp-chain*
